#!/bin/bash

# Update dependencies.
go get -u -v -d

# The above line somehow unfollows the branch, so we need to manually re-follow it.
git checkout master
git pull

# Build and start the server.
go build -v && \
GOMAXPROCS=1 ./stuzzd -cpuprofile cpu-$BASHPID.prof -memprofile mem-$BASHPID.prof -numslots 2147483647
