#!/bin/bash

# Update dependencies.
go get -u -v -d

# The above line somehow unfollows the branch, so we need to manually re-follow it.
git checkout master
git pull

# Build.
go build -v

# And finally, start the server.
echo Starting server...
GOMAXPROCS=1 ./stuzzd -cpuprofile cpu-$BASHPID.prof -memprofile mem-$BASHPID.prof -numslots 100
